### ISSUE TITLE
indexerror

### ISSUE THREAD

**Issue by jfffgit** [Holipori/EKAID#13]
cannot test the model cause an indexerror occurs when using test_mimic.py
moreover,do u have wechat?Could you please tell me how to use these  codes?

**Comment by jfffgit** [comment]
![1716121624414](https://github.com/Holipori/EKAID/assets/169330898/4445e33b-435f-42a1-81c8-a5445866ef39)

**Comment by Holipori** [comment]
Hi,
This error is because your "cmb_bbox_di_feats.hdf5" file only contains features of 900 images. However, your defined test split indexes are referring to an index higher than this number. You might need to double-check your self-defined partial dataset indexes to align with each other.

I do have WeChat: Moxer_
