### ISSUE TITLE
The difference question only has one 'image_id'

### ISSUE THREAD

**Issue by ZuoZicheng** [Holipori/EKAID#15]
Hello, I have encountered a question in the mimic_gt_captions_train/val/test. json file.
1. Why is there only one 'image_id' for each sample, even for difference question?
2. How to find the corresponding image ID in the mimic-cxr-png folder based on 'image_id'

**Comment by Holipori** [comment]
Hi,

1. The `image_id` here does not actually mean an ID for an image. It functions more like a `question ID`. The reason it is named this way is because I borrowed COCO evaluation tools, so I’m following the COCO format.
2. The `image_id` points to the index of feature_idx in h5_label_file: `data/VQA_mimic_dataset.h5`. Then, the feature_idx corresponds to the index of the question record in `mimic_pair_questions.csv`. In summary, to obtain the `dicom_id` (image ID in the mimic-cxr-png folder) from `image_id`, follow these steps: (1) Get `feature_idx` in `VQA_mimic_dataset.h5` using `image_id`. (2) Retrieve the question record ID in `mimic_pair_questions.csv` using `feature_idx`. You can then obtain the “study_id” and the “ref_id” corresponding to the question. (3) Search for the `dicom_id` using "study_id” or “ref_id” in `mimic_all.csv`.

These three steps can be implemented through coding. You can refer to lines 210-211 in ./model/datasets/rcc_dataset_pos_mimic.py for the reference code. The `img_idx` in lines 210-211 is the `image_id` you are inquiring about. You can further modify the `get_image()` function to let it return the `dicom_id`.

**Comment by ZuoZicheng** [comment]
Thank you very much for your timely and detailed answer! This has been very helpful to me, and I would like to express my sincere gratitude once again!
